# Generated by Django 4.0.4 on 2022-06-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('temporadas', models.IntegerField()),
                ('episodios', models.IntegerField()),
                ('añoEstreno', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('añoPublicacion', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('añoPublicacion', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.IntegerField()),
                ('añoEstreno', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('temporadas', models.IntegerField()),
                ('episodios', models.IntegerField()),
                ('añoEstreno', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
    ]
